DROP TABLE IF EXISTS DICOMRadiomicFeatureValue;
DROP TABLE IF EXISTS DICOMRadiomicFeature;
DROP TABLE IF EXISTS DICOMRadiomicClass;
DROP TABLE IF EXISTS DICOMRadiomicFilter;
DROP TABLE IF EXISTS DICOMRadiomics;
DROP TABLE IF EXISTS DICOMSeriesROI;
DROP TABLE IF EXISTS DICOMROI;