CREATE TABLE DICOMSeriesROI
(
RoiId INTEGER,
SeriesInst VARCHAR,
Number INTEGER NOT NULL,
DicomSegFile VARCHAR,
PRIMARY KEY (RoiId, SeriesInst),
FOREIGN KEY (RoiId) REFERENCES DICOMROI(RoiId),
FOREIGN KEY (SeriesInst) REFERENCES DICOMSeries(SeriesInst)
);