CREATE TABLE DICOMRadiomics
(
RadiomicsId INTEGER PRIMARY KEY AUTOINCREMENT,
RadiomicPat	TEXT NOT NULL,
RadiomicSeriesOfImageSlicesModality TEXT NOT NULL,
RadiomicSeriesOfImageSlices TEXT NOT NULL, 
RadiomicRtstructSeries TEXT NOT NULL,
TimeOfCalculation TEXT DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY(RadiomicPat) REFERENCES DICOMPatients(PatientID),
FOREIGN KEY(RadiomicSeriesOfImageSlices) REFERENCES DICOMSeries(SeriesInst),
FOREIGN KEY(RadiomicRtstructSeries) REFERENCES DICOMSeries(SeriesInst)
);

CREATE TABLE DICOMRadiomicFilter
(
FilterId INTEGER PRIMARY KEY AUTOINCREMENT,
Name TEXT NOT NULL
);

CREATE TABLE DICOMRadiomicClass
(
ClassId INTEGER PRIMARY KEY AUTOINCREMENT,
ParentClassId NUMERIC,
Name TEXT NOT NULL,
FOREIGN KEY(ParentClassId) REFERENCES DICOMRadiomicClass(ClassId)
);

CREATE TABLE DICOMRadiomicFeature
(
RadiomicFeatureId INTEGER PRIMARY KEY AUTOINCREMENT,
RadiomicClassId NUMERIC NOT NULL,
Name TEXT NOT NULL,
FOREIGN KEY(RadiomicClassId) REFERENCES DICOMRadiomicClass(ClassId)
);

CREATE TABLE DICOMRadiomicFeatureValue
(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
RadiomicsId INTEGER NOT NULL,
RoiId INTEGER NOT NULL,
FilterId INTEGER NOT NULL,
ClassId INTEGER NOT NULL,
FeatureId INTEGER NOT NULL,
Value TEXT NOT NULL,
FOREIGN KEY(RadiomicsId) REFERENCES DICOMRadiomics(RadiomicsId),
FOREIGN KEY(RoiId) REFERENCES DICOMROI(RoiId),
FOREIGN KEY(FilterId) REFERENCES DICOMRadiomicFilter(FilterId),
FOREIGN KEY(ClassId) REFERENCES DICOMRadiomicClass(ClassId),
FOREIGN KEY(FeatureId) REFERENCES DICOMRadiomicFeature(RadiomicFeatureId)
);